const employerMenu = [
  {
    id: 1,
    name: "Dashboard",
    icon: "la-home",
    routePath: "/employers-dashboard/dashboard",
    active: "active",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 2,
    name: "Company Profile",
    icon: "la-user-tie",
    routePath: "/employers-dashboard/company-profile",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 3,
    name: "Post a New Job",
    icon: "la-paper-plane",
    routePath: "/employers-dashboard/post-jobs",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 4,
    name: "Manage Jobs",
    icon: "la-briefcase",
    routePath: "/employers-dashboard/manage-jobs",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 5,
    name: "All Applicants",
    icon: "la-file-invoice",
    routePath: "/employers-dashboard/all-applicants",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 6,
    name: "Forwrad Applications",
    icon: "la-bookmark-o",
    routePath: "/employers-dashboard/forward-resumes",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "EmployerId",
  },
  {
    id: 6,
    name: "Shortlisted Candidates",
    icon: "la-bookmark-o",
    routePath: "/employers-dashboard/shortlisted-candidates/shortlisted",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 6,
    name: "Sub Employer List",
    icon: "la-bookmark-o",
    routePath: "/employers-dashboard/subemployer",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 2,
    name: "Meeting links",
    icon: "la-user-tie",
    routePath: "/employers-dashboard/meetinglinks",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
    userAcitive: "",
  },
  {
    id: 10,
    name: "Change Password",
    icon: "la-lock",
    routePath: "/employers-dashboard/change-password",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 11,
    name: "Logout",
    icon: "la-sign-out",
    routePath: "/login",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
  {
    id: 12,
    name: "Delete Profile",
    icon: "la-trash",
    routePath: "/",
    active: "",
    permissions: ["view", "edit", "delete", "meeting", "export", "import", "reject", "approve","download"],
    paramtype: "",
  },
];
export default employerMenu;
